<?php

/**
 * @file
 */

declare(strict_types=1);

/**
 * Implements hook_theme().
 *
 * Https://www.drupal.org/docs/theming-drupal/twig-in-drupal/create-custom-twig-templates-for-custom-module.
 */
function op_text_theme($existing, $type, $theme, $path): array {
  return [
    'paragraph__text' => [
      'render element' => 'elements',
      'base hook' => 'paragraph',
    ],
    'field__node__field_additional_body_content' => [
      'render element' => 'elements',
      'base hook' => 'field',
    ],
  ];
}
