<?php

/**
 * @file
 * Install, update, and uninstall functions for Orbit Paragraphs Image.
 */

declare(strict_types=1);

use Drupal\Core\File\FileSystemInterface;
use Drupal\file\Entity\File;
use Drupal\file\FileInterface;
use Drupal\paragraphs\Entity\ParagraphsType;

/**
 * Implements hook_install().
 */
function op_image_install(): void {
  orbit_paragraphs_set_paragraph_type_icon(
    'op_image_inline_image',
    \Drupal::service('extension.list.module')->getPath('op_image') . '/assets/thumbnail.png',
  );
}
