<?php

declare(strict_types=1);

use Drupal\Core\File\FileSystemInterface;
use Drupal\file\Entity\File;
use Drupal\file\FileInterface;
use Drupal\paragraphs\Entity\ParagraphsType;

/**
 * Implements hook_install().
 */
function op_expanding_section_install(): void {
  orbit_paragraphs_set_paragraph_type_icon(
    'expanding_section',
    \Drupal::service('extension.list.module')->getPath('op_expanding_section') . '/assets/thumbnail.png',
  );
}

