<?php

declare(strict_types=1);

/**
 * Implements hook_theme().
 *
 * Https://www.drupal.org/docs/theming-drupal/twig-in-drupal/create-custom-twig-templates-for-custom-module.
 */
function op_expanding_section_theme($existing, $type, $theme, $path): array {
  return [
    'paragraph__expanding_section' => [
      'render element' => 'elements',
      'base hook' => 'paragraph',
    ],
    'paragraph__expanding_section_item' => [
      'render element' => 'elements',
      'base hook' => 'paragraph',
    ],
  ];
}
