<?php

/**
 * @file
 * Install, update, and uninstall functions for Orbit Paragraphs Image.
 */

declare(strict_types=1);

use Drupal\Core\File\FileSystemInterface;
use Drupal\file\Entity\File;
use Drupal\file\FileInterface;
use Drupal\paragraphs\Entity\ParagraphsType;

/**
 * Implements hook_install().
 */
function orbit_paragraphs_text_install(): void {
  orbit_paragraphs_set_paragraph_type_icon(
    'orbit_paragraphs_text',
    \Drupal::service('extension.list.module')->getPath('orbit_paragraphs_text') . '/assets/thumbnail.png',
  );
}

